services:
  qbittorrent:
    build: 
      context: .
      dockerfile: DockerfileEE
    image: rogunt/qbittorrentee:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qb/appdata:/config
      - ./qb/downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped